name: Weekly Release

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code $(git describe --tags --abbrev=0)..HEAD >/dev/null; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

      - name: Get draft release name
        id: get_release_name
        run: |
          # Fetch the list of draft releases from GitHub API
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100")

          # Extract the name of the first draft release (if any)
          release_name=$(echo "$response" | jq -r '.[] | select(.draft == true) | .name')

          echo "::set-output name=release_name::$release_name"

      - name: Publish release draft
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          # Add your code to create a draft release here
