name: Publish docs

on:
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup config
        uses: athackst/athackst.mkdocs@main
      - name: Get version
        uses: ./.github/actions/package-version
        id: package-version
      - name: Build and push docs to gh-pages
        uses: athackst/mkdocs-simple-plugin@main
        with:
          version: v${{ steps.package-version.outputs.current-version }}
          default_version: ${{ github.event.release.tag_name }}
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: site
