name: Publish docs

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup config
        uses: athackst/athackst.mkdocs@main
      - name: Publish dev docs
        uses: athackst/mkdocs-simple-plugin@main
        with:
          version: dev
      - name: Publish release docs
        if: ${{ github.event.release.tag_name }}
        uses: athackst/mkdocs-simple-plugin@main
        with:
          version: ${{ github.event.release.tag_name }} latest
          default_version: ${{ github.event.release.tag_name }}
      - name: Htmlproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: site
          url_swap: |
            ^\/${{ github.event.repository.name }}:
            ^\/dev:
            ^\/${{ github.event.release.tag_name }}:
